SELECT TITLE, NAME FROM ALBUM
INNER JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID;

SELECT CUS.FIRSTnAME, COUNT(*)
FROM INVOICE INV 
LEFT JOIN CUSTOMER CUS ON INV.CustomerId = CUS.CustomerId
GROUP BY CUS.CUSTOMERID;


SELECT *
FROM TRACK TRA
LEFT JOIN PLAYLISTTRACK PLT USING  (TRACKID)
inner join PLAYLIST PLAY ON PLAY.PLAYLISTID = PLT.PlaylistId AND PLay.NAME LIKE 'M%';

SELECT *
FROM PLAYLISTTRACK PLT USING  (TRACKID)
LEFT join PLAYLIST PLAY ON PLAY.PLAYLISTID = PLT.PlaylistId AND PLay.NAME LIKE 'M%';
WHERE PLAY.ME='M%';

SELECT CUS.FIRSTNAME,inv.invoicedate,COUNT(T.TRACKID), SUM(INVl.quantity * invl.unitprice) FROM INVOICE INV
inner join CUSTOMER CUS ON CUS.CUSTOMERID=INV.CUSTOMERID
inner JOIN INVOICELINE INVL ON INVL.INVOICEID = INV.INVOICEID 
inner join TRACK T ON INVL.TRACKID = T.TRACKID group by cus.customerid;

CREATE VIEW VistaCarrito AS
SELECT
    U.Nombre AS NombreUsuario,
    C.ID AS ID_Carrito,
    C.Total AS TotalCarrito
FROM
    Carrito C
JOIN
    Usuario U ON U.ID = C.Usuario;

CREATE VIEW Productos_Stock AS
SELECT Nombre, Stock, Precio
FROM Producto;

CREATE VIEW Ordenes_Actuales AS
SELECT Fecha, Usuario, Total
FROM Ordenes;
