UPDATE Usuario SET Nombre = 'NuevoNombre1' WHERE ID = 1;
UPDATE Carrito SET Total = Total + 50 WHERE ID = 2;
UPDATE Vendedor SET Ventas = Ventas + 1 WHERE ID = 3;
UPDATE Producto SET Descripcion = 'NuevaDescripcion1' WHERE ID = 4;
UPDATE Categoria SET Categoria = 'NuevaCategoria1' WHERE ID_Producto = 5;
UPDATE Imagenes_Producto SET Imagen = 'NuevaURLImagen1' WHERE ID_Producto = 6;
UPDATE Reviews_Producto SET Calificacion = 4 WHERE ID = 7;
UPDATE Ordenes SET Fecha = '2023-01-01' WHERE ID = 8;
UPDATE Preguntas SET Titulo = 'NuevoTitulo1' WHERE ID = 9;
UPDATE Reviews_Vendedor SET Contenido = 'NuevoContenido1' WHERE ID = 10;
UPDATE Usuario SET Nombre = 'NuevoNombre2' WHERE ID = 11;
UPDATE Carrito SET Total = Total + 30 WHERE ID = 12;
UPDATE Vendedor SET Ventas = Ventas + 2 WHERE ID = 13;
UPDATE Producto SET Descripcion = 'NuevaDescripcion2' WHERE ID = 14;
UPDATE Categoria SET Categoria = 'NuevaCategoria2' WHERE ID_Producto = 15;
UPDATE Imagenes_Producto SET Imagen = 'NuevaURLImagen2' WHERE ID_Producto = 16;
UPDATE Reviews_Producto SET Calificacion = 5 WHERE ID = 17;
UPDATE Ordenes SET Fecha = '2023-02-01' WHERE ID = 18;
UPDATE Preguntas SET Titulo = 'NuevoTitulo2' WHERE ID = 19;
UPDATE Reviews_Vendedor SET Contenido = 'NuevoContenido2' WHERE ID = 20;
